export { default as Navbar } from './Navbar'
export { default as doctorNavbar } from './doctorNavbar'
export { default as Sidebar } from './Sidebar/index.vue'
export { default as doctorSidebar } from './doctorSidebar/index.vue'
export { default as TagsView } from './TagsView'
export { default as doctorTagsView } from './doctorTagsView'
export { default as AppMain } from './AppMain'
